version: '3'

services:
  app:
    image: roadsurfer_assignment:latest
    restart: "no"
    build:
      context: ./
      dockerfile: Dockerfile
      target: local
    volumes:
      - ".:/app"
    ports:
      - "7777:80"

  database:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Test123123
    ports:
      - "3311:3306"
