parameters:

services:

  _defaults:
    autowire: false
    autoconfigure: false

  Roadsurfer\Service\CurrentTimeProvider: ~

  Roadsurfer\Service\CounterGridService:
    calls:
      - [ setCurrentTimeProvider, [ '@Roadsurfer\Service\CurrentTimeProvider' ] ]
      - [ setEntityManager, [ '@doctrine.orm.default_entity_manager' ] ]

  Roadsurfer\Command\ExtendCounterGridCommand:
    calls:
      - [ setCounterGridService, [ '@Roadsurfer\Service\CounterGridService' ] ]
    tags:
      - { name: console.command }

  Roadsurfer\Validator\OrderConstraintValidator:
    calls:
      - [ setCounterGridService, [ '@Roadsurfer\Service\CounterGridService' ] ]
    tags:
      - { name: validator.constraint_validator }