parameters:

services:

  _defaults:
    autowire: false
    autoconfigure: false

  Roadsurfer\Service\CurrentTimeProvider: ~

  Roadsurfer\Service\CounterGridService:
    calls:
      - [ setCurrentTimeProvider, [ '@Roadsurfer\Service\CurrentTimeProvider' ] ]
      - [ setEntityManager, [ '@doctrine.orm.default_entity_manager' ] ]

  Roadsurfer\Command\ExtendCounterGridCommand:
    calls:
      - [ setCounterGridService, [ '@Roadsurfer\Service\CounterGridService' ] ]
    tags:
      - { name: console.command }

  Roadsurfer\Validator\OrderConstraintValidator:
    calls:
      - [ setCounterGridService, [ '@Roadsurfer\Service\CounterGridService' ] ]
      - [ setCurrentTimeProvider, [ '@Roadsurfer\Service\CurrentTimeProvider' ] ]
    tags:
      - { name: validator.constraint_validator }


  Roadsurfer\Controller\ApiController:
    public: true
    calls:
      - [ setCounterGridService, [ '@Roadsurfer\Service\CounterGridService' ] ]
      - [ setFormFactory, [ '@form.factory' ] ]
      - [ setEntityManager, [ '@doctrine.orm.default_entity_manager' ] ]
      - [ setCurrentTimeProvider, ['@Roadsurfer\Service\CurrentTimeProvider']]

  Roadsurfer\DataFixtures\AppFixtures:
    calls:
      - [ setCounterGridService, [ '@Roadsurfer\Service\CounterGridService' ] ]
    tags:
      - { name: doctrine.fixture.orm }

  Roadsurfer\Form\OrderType:
    calls:
      - [ setEntityManager, [ '@doctrine.orm.default_entity_manager' ] ]
    tags:
      - { name: form.type, alias: Roadsurfer\Form\OrderType }

  Roadsurfer\Form\OrderEquipmentCounterType:
    calls:
      - [ setEntityManager, [ '@doctrine.orm.default_entity_manager' ] ]
    tags:
      - { name: form.type, alias: Roadsurfer\Form\OrderEquipmentCounterType }


  Roadsurfer\Listener\JsonResponseExceptionListener:
    tags:
      - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

  Roadsurfer\Listener\ApiControllerListener:
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }